---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true



platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[minitest-handler]

suites:
- name: notifying_block
  run_list:
  - recipe[poise_test::notifying_block]
